version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "${APP_PORT}:80"  # Expose app port to host, use APP_PORT from .env
        volumes:
            - .:/var/www/html  # Sync local code to the container
            - ./storage:/var/www/html/storage
            - ./bootstrap/cache:/var/www/html/bootstrap/cache
        env_file:
            - .env
        networks:
            - ercaspayadmin
        command: |
            bash -c "sed -i 's|;listen = 127.0.0.1:9000|listen = 0.0.0.0:9000|' /usr/local/etc/php-fpm.d/www.conf && php-fpm"  # Modify the correct PHP-FPM config

    nginx:
        image: nginx:latest
        ports:
            - "${APP_NGINX_PORT}:80"  # Expose Nginx port 80 to host port 8080
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config
        depends_on:
            - app  # Ensure app container starts before Nginx
        networks:
            - ercaspayadmin

networks:
    ercaspayadmin:
        driver: bridge  # Use the bridge network driver for internal communication
